@startuml

title __UTIL's Class Diagram__\n

  package Util {
    class Consts {
        {static} + COVER_IMAGE : int
        {static} + SECRET_IMAGE : int
        {static} + SHARED_PREF_NAME : String
        {static} + PREF_COVER_PATH : String
        {static} + PREF_COVER_IS_SET : String
        {static} + MESSAGE_TYPE : String
        {static} + MESSAGE_BITS : String
        {static} + TYPE_TEXT : int
        {static} + TYPE_IMAGE : int
        {static} + TYPE_UNDEFINED : int
        {static} + EXTRA_STEGO_IMAGE_PATH : String
        {static} + EXTRA_SECRET_TEXT_RESULT : String
        {static} + EXTRA_SECRET_IMAGE_RESULT : String
        {static} + COLOR_RGB_END : Color
        {static} + COLOR_RGB_TEXT : Color
        {static} + COLOR_RGB_IMAGE : Color
        {static} + PASSES : boolean
        {static} + FAILS : boolean
        {static} + SUCCESS : boolean
        {static} + FAILURE : boolean
        {static} + NOT_FOUND : int
        {static} + NEW_LINE : String
        {static} + FILE_SEPARATOR : String
        {static} + PATH_SEPARATOR : String
        {static} + EMPTY_STRING : String
        {static} + SPACE : String
        {static} + TAB : String
        {static} + SINGLE_QUOTE : String
        {static} + PERIOD : String
        {static} + DOUBLE_QUOTE : String
        {static} + PORT : int
        {static} + SERVER_NAME : String
        - Consts()
    }
  }
  

  package Util {
    class Uty {
        {static} + zip()
        {static} + unZipIt()
        {static} + bytesHash()
        {static} + byteConcatenate()
        {static} + WriteMapToFile()
        {static} + writeByteToFile()
        {static} + fileToMap()
        {static} + remove()
        + bigToarray()
        + arrayTobig()
        {static} + byteToMap()
        {static} + xorWithKey()
        {static} + randomBig()
        {static} ~ concatenate()
        {static} + serialize()
        {static} + deserialize()
        {static} + writeImgToFile()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
